version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: auth-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  auth:
    image: auth-service:latest # ✅ the Jib-built image
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/yourdb
      SPRING_DATASOURCE_USERNAME: youruser
      SPRING_DATASOURCE_PASSWORD: yourpass
    logging:
      driver: "json-file"
  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /var/log:/var/log
      - ./promtail-config/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /run/docker.sock:/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    ports:
      - "3200:3200" # HTTP (query/api)
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP (optional if using HTTP)
    volumes:
      - ./tempo-config/tempo-config.yaml:/etc/tempo.yaml
    command: ["-config.file=/etc/tempo.yaml"]

volumes:
  postgres_data:
