package com.example.auth.controller;

import com.example.auth.dto.AuthResponseDto;
import com.example.auth.dto.LoginRequestDto;
import com.example.auth.dto.RegisterRequestDto;
import com.example.auth.dto.UserDto;
import com.example.auth.model.User;
import com.example.auth.model.UserPrincipal;

import com.example.auth.service.JwtService;
import com.example.auth.service.UserService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;

import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.*;


@RestController
@RequestMapping("/api/auth")
@RequiredArgsConstructor
@Tag(name = "Auth Controller", description = "Handles authentication and registration")
public class UserController {

    private final UserService userService;
    private final AuthenticationManager authenticationManager;
    private final JwtService jwtService;

    @GetMapping("/")
    @Operation(summary = "Welcome message for health check")
    public ResponseEntity<String> welcome() {
        return ResponseEntity.ok("Welcome to the Authentication Service");
    }
    
    @PostMapping("/register")
    @Operation(summary = "Register a new user")
    public ResponseEntity<AuthResponseDto> register(@Valid @RequestBody RegisterRequestDto request) {
        User user = new User();
        user.setUsername(request.getUsername());
        user.setEmail(request.getEmail());
        user.setPassword(request.getPassword());
        user.setRole(request.getRole());
        userService.saveUser(user);
        // Prepare Kafka event payload
        // UserCreatedEventDto event = new UserCreatedEventDto(
        //     user.getUserId(), // Assuming this is UUID and auto-generated by DB or service
        //     user.getEmail(),
        //     user.getRole()
        // );
        //if (eventPublisher != null) {
        // try {
        //     String json = objectMapper.writeValueAsString(event);
        //     JsonSchemaValidator.validate(json, userCreatedSchemaPath);
        //     eventPublisher.publish("user-created", user.getUserId().toString(), json);
        //     System.out.println("✅ Published user-created event");
        // } catch (Exception e) {
        //     System.err.println("❌ Failed to publish user-created event: " + e.getMessage());
        // }
        // } else {
        //     System.out.println("⚠️ Kafka disabled, skipping event publish.");
        // }
        return ResponseEntity.ok(new AuthResponseDto("User registered", null));
    }

    @PostMapping("/login")
    @Operation(summary = "Authenticate user and return JWT token")
    public ResponseEntity<AuthResponseDto> login(@Valid @RequestBody LoginRequestDto request) {
        try {
            Authentication auth = authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(request.getUsername(), request.getPassword())
            );

            if (auth.isAuthenticated() && auth.getPrincipal() instanceof UserPrincipal userPrincipal) {
                String token = jwtService.generateToken(userPrincipal);
                return ResponseEntity.ok(new AuthResponseDto("Login successful", token));
            }

        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED)
                                 .body(new AuthResponseDto("Invalid credentials", null));
        }

        return ResponseEntity.status(HttpStatus.UNAUTHORIZED)
                             .body(new AuthResponseDto("Login failed", null));
    }

    @GetMapping("/current-user")
    @Operation(summary = "Get currently authenticated user's details")
    public ResponseEntity<UserDto> getCurrentUser() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();

        if (authentication != null && authentication.isAuthenticated() &&
            authentication.getPrincipal() instanceof UserPrincipal userPrincipal) {

            User user = userPrincipal.getUser();
            UserDto userDto =UserDto.builder()
                    .userId(user.getUserId())
                    .username(user.getUsername())
                    .email(user.getEmail())
                    .role(user.getRole())
                    .build();
            return ResponseEntity.ok(userDto);
        }

        return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
    }


    @GetMapping("/admin-only")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Accessible only by admin users")
    public ResponseEntity<String> adminOnly() {
        return ResponseEntity.ok("Welcome, Admin!");
    }
    
    
	

    

}
